server: 
  port: 8765
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-8765.com
    prefer-ip-address: true 
 
 
zuul: 
  ignored-services: microservice-emp #忽略全部:"*"
#  prefix: /service
  routes: 
    mydept.serviceId: microservice-emp
    mydept.path: /myemp/**
 
info:
  service.name: microservice-emp 
  service.desc: This service provides the invocation of the employee.   
  build.artifactId: microservice-zuul-gateway-8765
  build.version: 0.0.1-SNAPSHOT    

